"""Emit the manuscript tables (paper/media/tables/*.tex) and a numbers file from the frozen analysis.

Every number in these tables is read from results/v2/analysis/{C,S}/... (snapshot 1381bdd759f9), except the
PatchCamelyon table, which is read from the `pcam` field of the frozen run records, and the SimCLR x SAM interaction,
which is computed from per_run_id.csv. Nothing is typed by hand.

    python src/v2/paper_tables.py --analysis results/v2/analysis --snap $V2/snap_final2_20261005 \
        --out paper/media/tables --numbers results/v2/analysis/paper_numbers.json
"""
import argparse
import glob
import json
import os
import sys

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from make_figures_v2 import ARM_LABEL, ARM_ORDER, TTA_LABEL, TRANSDUCTIVE, family  # noqa: E402

COHORTS = ["c17", "canine", "midog21sn", "midogpp"]
CLABEL = {"c17": "Camelyon17", "canine": "Canine cSCC", "midog21sn": "MIDOG 2021", "midogpp": "MIDOG++"}
CSHORT = {"c17": "C17", "canine": "Canine", "midog21sn": "MIDOG21", "midogpp": "MIDOG++"}
SEEDS = {"C": 5, "S": 3}
FAMILY_TEX = {0: "Reference and controls", 1: "Domain-aware training", 2: "Stain normalization and color",
              3: "Self-supervision", 4: "Sharpness-aware", 5: "Test-time adaptation",
              6: "Pretrained representations"}
FAMILY_ORDER = [0, 1, 2, 3, 4, 5, 6]
MAIN_PROBES = ("probe_resnet50_imagenet", "probe_resnet50_lunit_bt", "probe_vit_s16_lunit_dino")  # ladder probes go to the ladder figure


def tex_label(arm):
    if "@" in arm:
        t, a = arm.split("@", 1)
        return f"{TTA_LABEL.get(t, t)} ({tex_label(a)})".replace("$^{\\dagger}$", "") + "$^{\\dagger}$"
    lab = ARM_LABEL.get(arm, arm).replace("&", "\\&")
    return lab + ("$^{\\dagger}$" if arm in TRANSDUCTIVE else "")


def order(arms):
    def key(a):
        idx = ARM_ORDER.index(a) if a in ARM_ORDER else len(ARM_ORDER)
        return (FAMILY_ORDER.index(family(a)), idx, a)
    return sorted(arms, key=key)


def load(an, tier, cohort, kind, sel="id"):
    return pd.read_csv(os.path.join(an, tier, cohort, f"{kind}_{sel}.csv"))


# ---------------------------------------------------------------------------------------------------------------
def table_main(an, tier):
    """Worst-domain AUROC (rank) and mean AUROC per arm and cohort, ID-val selection."""
    S = {c: load(an, tier, c, "summary").set_index("arm") for c in COHORTS}
    R = {c: load(an, tier, c, "ranks").set_index("arm") for c in COHORTS}
    arms = order(set().union(*[set(S[c].index) for c in COHORTS]))
    best = {c: S[c]["worst"].max() for c in COHORTS}
    n_arms = {c: len(S[c]) for c in COHORTS}
    lines = []
    fam_prev = None
    for a in arms:
        fam = family(a)
        if fam != fam_prev:
            if fam_prev is not None:
                lines.append("\\addlinespace[2pt]")
            lines.append(f"\\multicolumn{{9}}{{@{{}}l}}{{\\emph{{{FAMILY_TEX[fam]}}}}}\\\\")
            fam_prev = fam
        cells = [tex_label(a)]
        for c in COHORTS:
            if a not in S[c].index:
                cells += ["--", "--"]
                continue
            w, m, rk = S[c].loc[a, "worst"], S[c].loc[a, "mean"], int(R[c].loc[a, "rank_worst"])
            ws = f"{w:.3f}"
            if abs(w - best[c]) < 1e-12:
                ws = f"\\textbf{{{ws}}}"
            cells += [f"{ws} ({rk})", f"{m:.3f}"]
        lines.append(" & ".join(cells) + " \\\\")
    head = " & ".join(["Arm"] + [f"\\multicolumn{{2}}{{c}}{{{CLABEL[c]} ($K={int(S[c]['K'].iloc[0])}$)}}"
                                 for c in COHORTS]) + " \\\\"
    cmid = "".join(f"\\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(4))
    sub = " & " + " & ".join(["worst (rank)", "mean"] * 4) + " \\\\"
    body = "\n".join(lines)
    return (f"% generated by src/v2/paper_tables.py from results/v2/analysis/{tier}/*/summary_id.csv, ranks_id.csv\n"
            "\\begin{tabular*}{\\tblwidth}{@{\\extracolsep{\\fill}}l*{4}{rr}@{}}\n\\toprule\n"
            f"{head}\n{cmid}\n{sub}\n\\midrule\n{body}\n\\bottomrule\n\\end{{tabular*}}\n"), \
        {c: n_arms[c] for c in COHORTS}


# ---------------------------------------------------------------------------------------------------------------
def table_evidence(an):
    """Per tier and cohort: variance shares, contrasts against ERM and the K needed for a 0.05 gain."""
    rows, nums = [], {}
    for tier in ["S", "C"]:
        s = SEEDS[tier]
        for c in COHORTS:
            v = load(an, tier, c, "variance")
            ct = load(an, tier, c, "contrasts")
            p = load(an, tier, c, "power")
            p = p[p.ref == "erm"]
            K = int(ct.K.iloc[0])
            p0 = p[(p.seeds == s) & (p.rho == 0) & (p.delta == 0.05)]
            p5 = p[(p.seeds == s) & (p.rho == 0.5) & (p.keff_mode == "ratio") & (p.delta == 0.05)]
            erm = v[v.arm == "erm"].iloc[0]
            up = int(((ct.p < 0.05) & (ct.mean_diff > 0)).sum())
            dn = int(((ct.p < 0.05) & (ct.mean_diff < 0)).sum())
            hu = int(((ct.p_holm < 0.05) & (ct.mean_diff > 0)).sum())
            hd = int(((ct.p_holm < 0.05) & (ct.mean_diff < 0)).sum())
            top = ct.sort_values("mean_diff", ascending=False).iloc[0]
            d = dict(K=K, seeds=s, n_arms=len(ct), icc_median=float(v.icc_anova.median()),
                     icc_q1=float(v.icc_anova.quantile(.25)), icc_q3=float(v.icc_anova.quantile(.75)),
                     icc_lo_gt_half=int((v.icc_ci_lo > 0.5).sum()), icc_lo_zero=int((v.icc_ci_lo <= 0).sum()),
                     erm_icc=float(erm.icc_anova), erm_icc_ci=[float(erm.icc_ci_lo), float(erm.icc_ci_hi)],
                     erm_sd_domain=float(erm.sigma_domain_anova), erm_sd_run=float(erm.sigma_run_anova),
                     raw_up=up, raw_down=dn, holm_up=hu, holm_down=hd,
                     top_arm=top.arm, top_gain=float(top.mean_diff), top_n_improved=int(top.n_improved),
                     sd_delta_median=float(p0.sd_delta.median()),
                     # a required number of domains is rounded up (the median of an even count can be x.5)
                     kmin05_median=float(np.ceil(p0.K_min.median())),
                     kmin05_rho05_median=float(np.ceil(p5.K_min.median())))
            nums[f"{tier}/{c}"] = d
            rows.append(" & ".join([
                tier if c == "c17" else "", CSHORT[c], str(K),
                f"{d['icc_median']:.2f} [{d['icc_q1']:.2f}, {d['icc_q3']:.2f}]",
                f"{d['icc_lo_gt_half']}/{len(v)}",
                f"{d['erm_sd_domain']:.3f} / {d['erm_sd_run']:.3f}",
                f"{up} / {dn}", f"{hu} / {hd}",
                f"{tex_label(top.arm)} ({top.mean_diff:+.3f})",
                f"{d['sd_delta_median']:.3f}", f"{d['kmin05_median']:.0f} ({d['kmin05_rho05_median']:.0f})"]) + " \\\\")
        if tier == "S":
            rows.append("\\addlinespace[3pt]")
    body = "\n".join(rows)
    head = ("Tier & Cohort & $K$ & ICC median [IQR] & CI$_{\\text{lo}}>0.5$ & ERM $\\hat\\sigma_D$ / $\\hat\\sigma_R$"
            " & $p<0.05$ ($+$/$-$) & Holm ($+$/$-$) & Largest gain over ERM & $\\hat\\sigma_\\Delta$"
            " & $K_{0.05}$ \\\\")
    tex = ("% generated by src/v2/paper_tables.py from variance_id.csv, contrasts_id.csv, power_id.csv\n"
           "\\begin{tabular*}{\\tblwidth}{@{\\extracolsep{\\fill}}llrlrlrr>{\\raggedright\\arraybackslash}p{2.2cm}rr@{}}\n"
           f"\\toprule\n{head}\n\\midrule\n{body}\n\\bottomrule\n\\end{{tabular*}}\n")
    return tex, nums


# ---------------------------------------------------------------------------------------------------------------
def table_selection(an):
    rows, nums = [], {}
    for tier in ["S", "C"]:
        for c in COHORTS:
            sels = [s for s in ["id", "ood", "last", "oracle"]
                    if os.path.exists(os.path.join(an, tier, c, f"summary_{s}.csv"))]
            S = {s: load(an, tier, c, "summary", s).set_index("arm")["worst"] for s in sels}
            common = sorted(set.intersection(*[set(x.index) for x in S.values()]))
            cells = [tier if c == "c17" else "", CLABEL[c], str(len(common))]
            d = {"n_common": len(common)}
            for s in ["ood", "last", "oracle"]:
                if s in S:
                    tau = stats.kendalltau(S["id"][common], S[s][common]).statistic
                    cells.append(f"{tau:.2f}")
                    d[f"tau_{s}"] = float(tau)
                else:
                    cells.append("--")
            tops = []
            for s in ["id", "ood", "last", "oracle"]:
                if s in S:
                    t = S[s][common].idxmax()
                    d[f"top_{s}"] = t
                    tops.append(t)
            same = len(set(tops)) == 1
            d["same_top"] = same
            cells.append("yes" if same else "no")
            nums[f"{tier}/{c}"] = d
            rows.append(" & ".join(cells) + " \\\\")
        if tier == "S":
            rows.append("\\addlinespace[3pt]")
    head = ("Tier & Cohort & Arms & $\\tau_b$ OOD-val & $\\tau_b$ last & $\\tau_b$ oracle & Same top arm \\\\")
    tex = ("% generated by src/v2/paper_tables.py from summary_{id,ood,last,oracle}.csv (worst-domain AUROC)\n"
           "\\begin{tabular*}{\\tblwidth}{@{\\extracolsep{\\fill}}llrrrrl@{}}\n"
           f"\\toprule\n{head}\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular*}\n")
    return tex, nums


# ---------------------------------------------------------------------------------------------------------------
def table_pcam(snap):
    rows = []
    for tier in ["C", "S"]:
        for f in glob.glob(os.path.join(snap, "runs", tier, "c17", "fold*", "*.json")):
            r = json.load(open(f))
            if r.get("phase") != "final":
                continue
            p = (r.get("pcam") or {}).get("id")
            if p:
                rows.append(dict(tier=tier, arm=r["arm"], fold=r["fold"], seed=r["seed"], auroc=p["auroc"]))
    df = pd.DataFrame(rows)
    g = df.groupby(["tier", "arm", "fold"]).auroc.mean().unstack("fold")
    out, nums = {}, {}
    for tier in ["C", "S"]:
        t = g.loc[tier]
        t = t[[not a.startswith("probe_") or a in MAIN_PROBES for a in t.index]]
        res = pd.DataFrame({"mean": t.mean(axis=1), "min": t.min(axis=1)}).sort_values("mean", ascending=False)
        nums[tier] = {a: dict(mean=float(r["mean"]), min=float(r["min"])) for a, r in res.iterrows()}
        out[tier] = res
    arms = order(set(out["C"].index) | set(out["S"].index))
    lines = []
    for a in arms:
        cells = [tex_label(a)]
        for tier in ["C", "S"]:
            if a in out[tier].index:
                cells += [f"{out[tier].loc[a, 'mean']:.3f}", f"{out[tier].loc[a, 'min']:.3f}"]
            else:
                cells += ["--", "--"]
        lines.append(" & ".join(cells) + " \\\\")
    tex = ("% generated by src/v2/paper_tables.py from the pcam field of the frozen run records (ID-val checkpoint)\n"
           "\\begin{tabular*}{\\tblwidth}{@{\\extracolsep{\\fill}}lrrrr@{}}\n\\toprule\n"
           " & \\multicolumn{2}{c}{Compact tier} & \\multicolumn{2}{c}{Standard tier} \\\\\n"
           "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
           "Arm & mean & min over folds & mean & min over folds \\\\\n\\midrule\n"
           + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular*}\n")
    return tex, nums


# ---------------------------------------------------------------------------------------------------------------
def interaction(an):
    nums = {}
    for c in COHORTS:
        a = load(an, "C", c, "per_run")
        m = a.groupby(["arm", "domain"]).metric.mean().unstack(0)
        inter = m["simclr_sam"] - m["simclr"] - m["sam"] + m["erm"]
        K = len(inter)
        se = inter.std(ddof=1) / np.sqrt(K)
        t = stats.t.ppf(.975, K - 1)
        nums[c] = dict(K=K, per_domain={k: float(v) for k, v in inter.items()}, mean=float(inter.mean()),
                       ci=[float(inter.mean() - t * se), float(inter.mean() + t * se)],
                       p=float(stats.ttest_1samp(inter, 0).pvalue))
    return nums


def table_response(an):
    """Oldham's correlation of each arm with ERM: sign counts, Pitman-Morgan and exact permutation tests."""
    rows = []
    for tier in ["S", "C"]:
        for c in COHORTS:
            r = load(an, tier, c, "response")
            rows.append(" & ".join([tier if c == "c17" else "", CLABEL[c], str(int(r.K.iloc[0])),
                                    f"{int((r.oldham_r < 0).sum())}/{len(r)}", f"{r.oldham_r.median():+.2f}",
                                    str(int((r.pm_p < 0.05).sum())), f"{r.perm_p.min():.3f}"]) + " \\\\")
        if tier == "S":
            rows.append("\\addlinespace[3pt]")
    head = ("Tier & Cohort & $K$ & $r<0$ & median $r$ & Pitman--Morgan $p<0.05$ & smallest exact $p$ \\\\")
    return ("% generated by src/v2/paper_tables.py from response_id.csv\n"
            "\\begin{tabular*}{\\tblwidth}{@{\\extracolsep{\\fill}}llrrrrr@{}}\n"
            f"\\toprule\n{head}\n\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular*}\n")


def extra_numbers(an, sens):
    """Numbers quoted in the text that are not in a table."""
    out = {}
    for tier in ["C", "S"]:
        for c in COHORTS:
            pr = load(an, tier, c, "per_run")
            erm = pr[pr.arm == "erm"].groupby("domain").metric
            sm = load(an, tier, c, "summary").set_index("arm")
            rk = load(an, tier, c, "ranks").set_index("arm")
            wd = load(an, tier, c, "summary").worst_domain.value_counts()
            width = rk.rank_worst_domain_ci.map(lambda x: json.loads(x)[1] - json.loads(x)[0])
            width_seed = rk.rank_worst_seed_ci.map(lambda x: json.loads(x)[1] - json.loads(x)[0])
            rs = load(an, tier, c, "response")
            out[f"{tier}/{c}"] = dict(
                erm_seed_range_by_domain={d: [float(g.min()), float(g.max())] for d, g in erm},
                erm_worst=float(sm.loc["erm", "worst"]), erm_worst_domain=sm.loc["erm", "worst_domain"],
                erm_mean=float(sm.loc["erm", "mean"]),
                most_common_worst_domain=[wd.index[0], int(wd.iloc[0]), int(wd.sum())],
                rank_ci_width_domain_median=float(width.median()),
                rank_ci_width_seed_median=float(width_seed.median()),
                pbest_top=[rk.pbest_worst_domain.idxmax(), float(rk.pbest_worst_domain.max())],
                ece_erm=float(sm.loc["erm", "ece_mean"]),
                ece_best=[sm.ece_mean.idxmin(), float(sm.ece_mean.min())],
                ece_tia_vs_jitter=[float(sm.loc["tia_style", "ece_mean"]), float(sm.loc["he_jitter", "ece_mean"])],
                oldham_negative=int((rs.oldham_r < 0).sum()), n_response=len(rs),
                pm_p_lt05=int((rs.pm_p < 0.05).sum()), perm_p_lt05=int((rs.perm_p < 0.05).sum()),
                perm_p_min=float(rs.perm_p.min()))
    # agreement between the tiers for the arms run at both
    for c in COHORTS:
        a = load(an, "C", c, "summary").set_index("arm")["worst"]
        b = load(an, "S", c, "summary").set_index("arm")["worst"]
        common = sorted(set(a.index) & set(b.index))
        out[f"tier_tau/{c}"] = dict(n=len(common), tau=float(stats.kendalltau(a[common], b[common]).statistic),
                                    arms=common)
    # MIDOG 2021 scale-normalization sensitivity (compact tier)
    f = os.path.join(sens, "C", "midog21", "summary_id.csv")
    if os.path.exists(f):
        u = pd.read_csv(f).set_index("arm")
        n = load(an, "C", "midog21sn", "summary").set_index("arm")
        common = sorted(set(u.index) & set(n.index))
        out["midog21_sens"] = dict(
            n=len(common),
            tau_worst=float(stats.kendalltau(n.loc[common, "worst"], u.loc[common, "worst"]).statistic),
            tau_mean=float(stats.kendalltau(n.loc[common, "mean"], u.loc[common, "mean"]).statistic),
            erm=[float(n.loc["erm", "worst"]), float(u.loc["erm", "worst"])],
            max_abs_worst_change=float((n.loc[common, "worst"] - u.loc[common, "worst"]).abs().max()))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--analysis", default="results/v2/analysis")
    ap.add_argument("--snap", default=os.path.join(os.environ.get("HISTOPATH_DATA", "data"), "v2/snap_final2_20261005"))
    ap.add_argument("--out", default="paper/media/tables")
    ap.add_argument("--sens", default="results/v2/analysis_sens")
    ap.add_argument("--numbers", default="results/v2/analysis/paper_numbers.json")
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    nums = {}
    for tier in ["S", "C"]:
        tex, n = table_main(a.analysis, tier)
        open(os.path.join(a.out, f"tab_main_{tier}.tex"), "w").write(tex)
        nums[f"n_arms_{tier}"] = n
    tex, nums["evidence"] = table_evidence(a.analysis)
    open(os.path.join(a.out, "tab_evidence.tex"), "w").write(tex)
    tex, nums["selection"] = table_selection(a.analysis)
    open(os.path.join(a.out, "tab_selection.tex"), "w").write(tex)
    tex, nums["pcam"] = table_pcam(a.snap)
    open(os.path.join(a.out, "tab_pcam.tex"), "w").write(tex)
    nums["simclr_sam_interaction_C"] = interaction(a.analysis)
    open(os.path.join(a.out, "tab_response.tex"), "w").write(table_response(a.analysis))
    nums["extra"] = extra_numbers(a.analysis, a.sens)
    json.dump(nums, open(a.numbers, "w"), indent=1)
    print("wrote", sorted(os.listdir(a.out)), "and", a.numbers)


if __name__ == "__main__":
    main()
